In [1]:
from typing import List, Tuple, Set, Dict
import math
import heapq

from copy import deepcopy
from collections import defaultdict, namedtuple
import sys
from collections import deque, Counter
import numpy as np



In [2]:
'''

Given an integer array, check if it represents min-heap or not.

Input : [2, 3, 4, 5, 10, 15]
Output: True
Explanation: The input represents a min-heap.

		   2
		 /   \
		/	  \
	   3	   4
	  / \     /
	 /   \   /
	5	 10 15

Input : [2, 10, 4, 5, 3, 15]
Output: False
Explanation: The input is not a min-heap, as it violate the heap property.

		   2
		 /   \
		/	  \
	   10	   4
	  / \	  /
	 /   \   /
	5	  3 15

'''



class Solution:
	def checkMinHeap(self, nums: List[int]) -> bool:
		if not nums:
			return True

		n = len(nums)
		level = 0

		is_check_min = True
		q = deque()
		q.append((0, nums[0]))
		while q:
			i, x = q.popleft()
			left_i, right_i = 2*i +1, 2*i + 2
			left, right = nums[left_i] if left_i < n else None, nums[right_i] if right_i < n else None

			if left is not None:
				if left < x:
					return False
				q.append((left_i, left))
			
			if right is not None:
				if right < x:
					return False
				q.append((right_i, right))


		return is_check_min

Solution().checkMinHeap([-2, 1, 5, 9, 4, 7, 6])

True

In [3]:
'''

Given an array representing a max-heap, in-place convert it into the min-heap in linear time.

Input: [9, 4, 7, 1, -2, 6, 5]

		   9
		 /   \
		/	  \
	   4	   7
	  / \	  / \
	 /   \   /   \
	1	 -2 6	  5


Output: [-2, 1, 5, 9, 4, 6, 7]

		   -2
		 /	  \
		/	   \
	   1		5
	  / \	   / \
	 /   \	  /   \
	9	  4  6	   7		or, any other valid min-heap.

'''

class Solution:
    def left(self, i):
        return 2*i + 1
    
    def right(self, i):
        return 2*i + 2

    def convert(self, nums: List[int]) -> None:
        n = len(nums)
        if n == 0:
            return
        q = deque()
        i = n // 2
        q.append(i)
        while q:
            i = q.popleft()
            
            if i < 0:
                break
            left_i, right_i = self.left(i), self.right(i)
            left = None if left_i >= n else nums[left_i]
            right = None if right_i >= n else nums[right_i]
            
            smallest = i
            if left is not None:
                if left < nums[smallest]:
                    smallest = left_i
            if right is not None:
                if right < nums[smallest]:
                    smallest = right_i
            
            if smallest != i:
                nums[smallest], nums[i] = nums[i], nums[smallest]
                q.appendleft(smallest)
            q.append(i-1)
            
        return nums

Solution().convert([9, 4, 7, 1, -2, 6, 5])

[-2, 1, 5, 9, 4, 6, 7]

In [4]:
'''

Given an integer array, find k'th smallest element in the array where k is a positive integer less than or equal to the length of array.

Input : [7, 4, 6, 3, 9, 1], k = 3
Output: 4
Explanation: The 3rd smallest array element is 4

Input : [1, 5, 2, 2, 2, 5, 5, 4], k = 5
Output: 4
Explanation: The 5th smallest array element is 4

'''


class Solution:
    def findKthSmallest(self, nums: List[int], k: int) -> int:
        n = len(nums)
        if k > n:
            return -1
        heapq.heapify(nums)
        i = 0
        while nums:
            el = heapq.heappop(nums)
            i += 1
            if i == k:
                return el


Solution().findKthSmallest([7, 4, 6, 3, 9, 1], 3)
        

4

In [5]:
'''

Given an integer array, find k'th largest element in the array where k is a positive integer less than or equal to the length of array.

Input : [7, 4, 6, 3, 9, 1], k = 2
Output: 7
Explanation: The 2nd largest array element is 7

Input : [1, 5, 2, 2, 2, 5, 5, 4], k = 4
Output: 4
Explanation: The 4th largest array element is 4

'''



class Solution:
    def findKthLargest(self, nums: List[int], k: int) -> int:
        n = len(nums)
        if k > n:
            return -1
        heapq._heapify_max(nums)
        print(nums)
        i = 0
        while nums:
            el = heapq._heappop_max(nums)
            i += 1
            if i == k:
                return el

Solution().findKthLargest([7, 4, 6, 3, 9, 1], k = 2)


[9, 7, 6, 3, 4, 1]


7

In [6]:
'''
# TODO
Given an infinite stream of integers, return the element representing the k'th largest element in the stream.

Input: k = 3, nextInt = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...]
Output : [-1, -1, 1, 2, 3, 4, 5, 6, 7, 8, ...]

Here, `k` is constant for each run and `nextInt` is the next integer in the infinite stream. The solution should return the next k'th largest element, and return -1 when the stream has fewer elements than `k`.

'''

class MinHeap:

    def __init__(self, k):
        self.k = k
        self.pool = []
    
    def add(self, n):
        if len(self.pool) < self.k:
            heapq.heappush(self.pool, n)
        elif self.pool[0] < n:
            heapq.heappushpop(self.pool, n)
        print(self.pool)
        if len(self.pool) == self.k:
            return self.pool[0]
        else:
            return -1

class Solution:
    def findKthLargest(self, k: int, nextInt: int) -> int:
        if not hasattr(self, 'min_heap'):
            self.min_heap = MinHeap(k)

        return self.min_heap.add(nextInt)
nextInt = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
s = Solution()
while nextInt:
    print(s.findKthLargest(3, nextInt.pop(0)))



[1]
-1
[1, 2]
-1
[1, 2, 3]
1
[2, 4, 3]
2
[3, 4, 5]
3
[4, 6, 5]
4
[5, 6, 7]
5
[6, 8, 7]
6
[7, 8, 9]
7
[8, 10, 9]
8


In [7]:
'''

Given an infinite stream of integers, return the element representing the k'th largest element in the stream.

Input: k = 3, nextInt = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...]
Output : [-1, -1, 1, 2, 3, 4, 5, 6, 7, 8, ...]

Here, `k` is constant for each run and `nextInt` is the next integer in the infinite stream. The solution should return the next k'th largest element, and return -1 when the stream has fewer elements than `k`.

'''


class MinHeap:

    def __init__(self, k):
        self.k = k
        self.pool = []
    
    def add(self, n):
        if len(self.pool) < self.k:
            heapq.heappush(self.pool, n)
        elif self.pool[0] < n:
            heapq.heappushpop(self.pool, n)
        if len(self.pool) == self.k:
            return self.pool[0]
        else:
            return -1

class Solution:
    def findKthLargest(self, k: int, nextInt: int) -> int:
        if not hasattr(self, 'min_heap'):
            self.min_heap = MinHeap(k)

        return self.min_heap.add(nextInt)




In [8]:
'''

Given `M` sorted lists of variable length, merge them efficiently in sorted order.

Input:

mat = [
	[10, 20, 30, 40],
	[15, 25, 35],
	[27, 29, 37, 48, 93],
	[32, 33]
]

Output: [10, 15, 20, 25, 27, 29, 30, 32, 33, 35, 37, 40, 48, 93]

'''



class Solution:
    def mergeSortedLists(self, lists: List[List[int]]) -> List[int]:
        if not lists:
            return lists
        
        if lists and not lists:
            return lists
        
        res = []
        q = []
        for i, ls in enumerate(lists):
            if ls:
                q.append((ls[0], i))
                ls.pop(0)

        heapq.heapify(q)

        while q:
            it, list_index = heapq.heappop(q)
            res.append(it)

            ls = lists[list_index]
            if ls:
                el = ls.pop(0)
                heapq.heappush(q, (el, list_index))
            
        return res

Solution().mergeSortedLists( [
	[10, 20, 30, 40],
	[15, 25, 35],
	[27, 29, 37, 48, 93],
	[32, 33]
]
)


[10, 15, 20, 25, 27, 29, 30, 32, 33, 35, 37, 40, 48, 93]

In [9]:
'''
# TODO
Given n ropes of different lengths, connect them into a single rope with minimum cost. Assume that the cost to connect two ropes is the same as the sum of their lengths.

Input: [5, 4, 2, 8]
Output: 36
Explanation: The total cost for connecting all ropes is 6 + 11 + 19 = 36.

[5, 4, 2, 8] –> First, connect ropes of lengths 4 and 2 that will cost 6.
[5, 6, 8]    –> Next, connect ropes of lengths 5 and 6 that will cost 11.
[11, 8]      –> Finally, connect the remaining two ropes that will cost 19.

'''


class Solution:
        

    def findMinCost(self, prices: List[int]) -> int:
        heapq.heapify(prices)
 
        cost = 0
    
        while len(prices) > 1:
    
            x = heapq.heappop(prices)
            y = heapq.heappop(prices)
    
            total = x + y
            heapq.heappush(prices, total)
    
            cost += total
    
        return cost
Solution().findMinCost( [5, 4, 2, 8])


36

In [10]:
'''

Given an array of distinct integers, replace each array element by its corresponding rank in the array. The minimum array element has the rank 1; the second minimum element has a rank of 2, and so on.

Input : [10, 8, 15, 12, 6, 20, 1]
Output: [4, 3, 6, 5, 2, 7, 1]

Input : [0, 1, -1]
Output: [2, 3, 1]

'''


class Solution:
	def transform(self, nums: List[int]) -> None:
		if not nums:
			return
		s = [(el, i) for i, el in enumerate(nums)]
		heapq.heapify(s)
		i = 0
		n = len(nums)
		while i < n:
			el, j = heapq.heappop(s)
			nums[j] = i + 1
			i += 1

		return


In [11]:
'''

Given two sequences, find the length of the longest common subsequence (LCS) present in it. The LCS is the longest sequence which can be obtained from the first sequence by deleting some items and from the second sequence by deleting other items.

Input: X = 'ABCBDAB', Y = 'BDCABA'
Output: 4
Explanation: The LCS are 'BDAB', 'BCAB', and 'BCBA', having length 4.

'''



class Solution:

    def recurse(self, X, Y, m, n, lookup):
        
        if m == 0 or n == 0:
            return 0
 
        key = (m, n)
    
        if key not in lookup:
    
            if X[m - 1] == Y[n - 1]:
                lookup[key] = self.recurse(X, Y, m - 1, n - 1, lookup) + 1
    
            else:
                lookup[key] = max(self.recurse(X, Y, m, n-1, lookup),
                                self.recurse(X, Y, m - 1, n, lookup)
                                )    
        return lookup[key]
               

    def findLCSLength(self, X: str, Y: str) -> int:
        if not len(X) or not len(Y):
            return 0
        lookup = dict()
        self.recurse(X, Y, len(X), len(Y), lookup)

        return lookup[(len(X), len(Y))]   

    
Solution().findLCSLength(X = 'xybyaxby', Y = 'xbyxybya')


6

In [12]:
'''

Given two sequences, return all longest common subsequence (LCS) present in it. The LCS is the longest sequence which can be obtained from the first sequence by deleting some items and from the second sequence by deleting other items.

Input: X = "XMJYAUZ", Y = "MZJAWXU"
Output: "MJAU"

The longest common subsequence is not guaranteed to be unique. If multiple longest common subsequence exists, the solution should return any one of them.

Input: X = "ABCBDAB", Y = "BDCABA"
Output: "BDAB" or "BCAB" or "BCBA"

'''

class Solution:

    def get_table(self, X, Y):
        m, n = len(X), len(Y)
        lookup = [[0 for j in range(n+1)] for i in range(m+1)]
        
        for i in range(1, m+1):
            for j in range(1, n+1):
                if X[i-1] == Y[j-1]:
                    lookup[i][j] = 1 + lookup[i-1][j-1]
                else:
                    lookup[i][j] = max(lookup[i][j-1], lookup[i-1][j])
        return lookup
    
    def recurse(self, X, Y, m, n, lookup):
        if m == 0 or n == 0:
            return ['']

        if X[m-1] == Y[n-1]:
            subset = self.recurse(X, Y, m-1, n-1, lookup)

            for i in range(len(subset)):
                subset[i] = subset[i] + X[m-1]
            return subset

        if lookup[m-1][n] > lookup[m][n-1]:
            return self.recurse(X, Y, m - 1, n, lookup)

        if lookup[m][n-1] > lookup[m-1][n]:
            return self.recurse(X, Y, m,  n- 1, lookup)
        
        top = self.recurse(X, Y, m-1, n, lookup)
        left = self.recurse(X, Y, m, n-1, lookup)

        return top + left

    def findLCS(self, X: str, Y: str) -> str:
        if not X or not Y:
            return ''
        lookup = self.get_table(X, Y)
        print(np.array(lookup))
        max_length = lookup[len(X)][len(Y)]
        subset = self.recurse(X, Y, len(X), len(Y), lookup)
        return subset[0]
Solution().findLCS(X = 'xybyaxby', Y = 'xbyxybya')


[[0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2]
 [0 1 2 2 2 2 3 3 3]
 [0 1 2 3 3 3 3 4 4]
 [0 1 2 3 3 3 3 4 5]
 [0 1 2 3 4 4 4 4 5]
 [0 1 2 3 4 4 5 5 5]
 [0 1 2 3 4 5 5 6 6]]


'xbyxby'

In [13]:
'''

Given three sequences, find the length of the longest common subsequence (LCS) present in it. The LCS is the longest subsequence that can be obtained from each of the given sequences by deleting zero or more characters.

Input: X = 'ABCBDAB', Y = 'BDCABA', Z = 'BADACB'
Output: 4
Explanation: The longest subsequence present in the given sequences in the same order is 'BDAB', having length 4.

'''


class Solution:
    def _findLCSLength(self, X, Y, Z):
        m, n, o = [len(x) for x in [X, Y, Z]]

        lookup = [[[0 for i in range(o+1)] for j in range(n+1)] for k in range(m+1)]

        for i in range(1, m+1):
            for j in range(1, n+1):
                for k in range(1, o+1):
                    if X[i-1] == Y[j-1] == Z[k-1]:
                        lookup[i][j][k] = 1 + lookup[i-1][j-1][k-1]
                    else:
                        lookup[i][j][k] = max(lookup[i-1][j][k],
                                              lookup[i][j-1][k],
                                              lookup[i][j][k-1],
                        )
        return lookup

    def findLCSLength(self, X: str, Y: str, Z: str) -> int:
        if not X or not Y or not Z:
            return 0
        lookup = self._findLCSLength(X, Y, Z)

        return lookup[len(X)][len(Y)][len(Z)]

Solution().findLCSLength( X = 'ABCBDAB', Y = 'BDCABA', Z = 'BADACB')

4

In [14]:
'''
def LCS(X, Y, m, n):
 
    maxLength = 0           # stores the max length of LCS
    endingIndex = m         # stores the ending index of LCS in `X`
 
    # `lookup[i][j]` stores the length of LCS of substring `X[0…i-1]` and `Y[0…j-1]`
    lookup = [[0 for x in range(n + 1)] for y in range(m + 1)]
 
    # fill the lookup table in a bottom-up manner
    for i in range(1, m + 1):
        for j in range(1, n + 1):
 
            # if the current character of `X` and `Y` matches
            if X[i - 1] == Y[j - 1]:
                lookup[i][j] = lookup[i - 1][j - 1] + 1
 
                # update the maximum length and ending index
                if lookup[i][j] > maxLength:
                    maxLength = lookup[i][j]
                    endingIndex = i
 
    # return longest common substring having length `maxLength`
    return X[endingIndex - maxLength: endingIndex]


Given two strings, find the longest string that is a substring of both strings.

Input: X = 'ABABC', Y = 'BABCA'
Output: 'BABC'
Explanation: The longest common substring of strings 'ABABC' and 'BABCA' is 'BABC' having length 4. The other common substrings are 'ABC', 'A', 'AB', 'B', 'BA', 'BC', and 'C'.

'''



class Solution:
    

    def findLongestCommonSubstring(self, X: str, Y: str) -> str:
        if not X or not Y:
            return ''

        m, n = len(X), len(Y)
        cs = ''
        for i in range(m):
            for j in range(n):
                if X[i] == Y[j]:
                    count = 0
                    r, s = i, j
                    while r >= 0 and s >= 0 and X[r] == Y[s]:
                        count +=1
                        r -= 1
                        s -= 1
                    if count > len(cs):
                        cs = X[i-count+1:i+1]

            
    
        return cs

Solution().findLongestCommonSubstring(X = 'ADCB', Y = 'ABCD')

'A'

In [15]:
'''

Given a sequence, find the longest subsequences of it that is also a palindrome.

Input: 'ABBDCACB'
Output: 5
Explanation: The longest palindromic subsequence is 'BCACB', having length 5.

'''


class Solution:
    def recurse(self, s, i, j, keys):
        if i > j:
            return 0
        k = (i, j)
        if k not in keys:
            if i == j:
                keys[k] = 1
                return keys[k]
            if s[i] == s[j]:
                keys[k] = 2 + self.recurse(s, i+1, j-1, keys)
            else:
                keys[k] = max(self.recurse(s, i+1, j, keys), self.recurse(s, i, j-1, keys))
        return keys[k]

    def findLPSLength(self, s: str) -> int:
        if not s:
            return 0
        i, j = 0, len(s) - 1
        return self.recurse(s, i, j, dict())

Solution().findLPSLength('ABBDCACB')

5

In [54]:
'''
Given a sequence, find the length of the longest subsequence of it that occurs at least twice where the repeated characters should holds a different index in the sequence.

Input: 'ATACTCGGA'
Output: 4
Explanation: The longest repeating subsequence is 'ATCG', having length 4.

'A' 'T'  A  'C'  T   C  'G'  G   A
 A   T  'A'  C  'T' 'C'  G  'G'  A

Input: 'YBYXBXBB'
Output: 5
Explanation: The longest repeating subsequence is 'YBXBB', having length 5.

'Y' 'B'  Y  'X' 'B'  X  'B'  B
 Y   B  'Y'  X  'B' 'X' 'B' 'B'

'''


class Solution:
    
    def find_recurse(self, s, i, j, keys):
        if i < 0 or j < 0:
            return 0
        if (i, j) in keys:
            return keys[(i, j)]
        if i != j and s[i] == s[j]:
            keys[(i, j)] = 1 + self.find_recurse(s, i-1, j-1, keys)

            return keys[(i, j)]

        max_length = max([self.find_recurse(s, i-1, j, keys),
                          self.find_recurse(s, i, j-1, keys)
                          ])
        keys[(i, j)] = max_length
        
        return keys[(i, j)]
        
            
            
    def findLRSLength(self, s: str) -> int:
        if not s or len(s) == 1:
            return 0
        length = 0
        keys = dict()
        lrs = self.find_recurse(s, len(s) - 1, len(s) - 1, keys)
        return lrs


Solution().findLRSLength('ATACTCGGA')



4

In [68]:
'''

Given two sequences, find the length of the shortest supersequence 'Z' of given sequences 'X' and 'Y' such that both 'X' and 'Y' are subsequences of 'Z'.

Input: X = 'ABCBDAB', Y = 'BDCABA'
Output: 9
Explanation: The SCS are 'ABCBDCABA', 'ABDCABDAB', and 'ABDCBDABA', having length 9.

'''



class Solution:
    
    def get_shortest(self, x, y, m, n, keys, items):
        if m < 0 or n < 0:
            if m > n:
                return m+1, x[:m+1]
            else:
                return n+1, y[:n+1] 

        if (m, n) in keys:
            return keys[(m, n)], items[(m, n)]
        
        
        if x[m] == y[n]:
            count, item = self.get_shortest(x, y, m-1, n-1, keys, items)
            keys[(m, n)] = 1 + count
            items[(m, n)] = item + x[m]
            return keys[(m, n)], items[(m, n)]
        count1, item1 = self.get_shortest(x, y, m-1, n, keys, items)
        count2, item2 = self.get_shortest(x, y, m, n-1, keys, items)
        
        if count1 < count2:
            count = count1
            item = item1 + x[m]
        else:
            count = count2
            item = item2 + y[n]
    
    
        count += 1
        keys[(m,n )] = count
        items[(m,n )] = item
                
        return keys[(m, n)], item
    
    def findSCSLength(self, X: str, Y: str) -> int: 
        keys = dict()
        items = dict()
        count, item = self.get_shortest(X, Y, len(X) - 1, len(Y) - 1, keys, items)
        print(items)
        return count


Solution().findSCSLength( X = 'ABCBDAB', Y = 'BDCABA')

ABCBDAB BDCABA
ABCBDAB BDCABA
ABCBDAB BDCABA
ABCBDAB BDCABA
{(0, 3): 'BDCA', (0, 0): 'AB', (0, 1): 'ABD', (0, 2): 'ABDC', (1, 0): 'AB', (1, 1): 'ABD', (1, 2): 'ABDC', (1, 3): 'ABDCA', (2, 2): 'ABDC', (2, 3): 'ABDCA', (3, 4): 'ABDCAB', (2, 0): 'ABC', (2, 1): 'ABCD', (3, 0): 'ABCB', (3, 1): 'ABCBD', (3, 2): 'ABDCB', (3, 3): 'ABDCBA', (4, 1): 'ABCBD', (4, 2): 'ABCBDC', (4, 3): 'ABCBDCA', (4, 4): 'ABDCABD', (5, 5): 'ABDCABDA', (5, 3): 'ABCBDCA', (6, 4): 'ABCBDCAB', (6, 5): 'ABCBDCABA'}


9

In [64]:
'''

Given two sequences, find the length of the shortest supersequence 'Z' of given sequences 'X' and 'Y' such that both 'X' and 'Y' are subsequences of 'Z'.

The shortest common supersequence is not guaranteed to be unique. If multiple shortest common supersequence exists, the solution should return any one of them.

Input: X = "ABCBDAB", Y = "BDCABA"
Output: "ABCBDCABA" or "ABDCABDAB" or "ABDCBDABA"

'''


class Solution:
	def get_shortest(self, x, y, m, n, keys, items):
		if m < 0 or n < 0:
			if m > n:
				return m+1, x[:m+1]
			else:
				return n+1, y[:n+1] 

		if (m, n) in keys:
			return keys[(m, n)], items[(m, n)]
		
		
		if x[m] == y[n]:
			count, item = self.get_shortest(x, y, m-1, n-1, keys, items)
			keys[(m, n)] = 1 + count
			items[(m, n)] = item + x[m]
			return keys[(m, n)], items[(m, n)]
		count1, item1 = self.get_shortest(x, y, m-1, n, keys, items)
		count2, item2 = self.get_shortest(x, y, m, n-1, keys, items)
		
		if count1 < count2:
			count = count1
			item = item1 + x[m]
		else:
			count = count2
			item = item2 + y[n]


		count += 1
		keys[(m,n )] = count
		items[(m,n )] = item
				
		return keys[(m, n)], item

	def findSCS(self, X: str, Y: str) -> str:
		keys = dict()
		items = dict()
		count, item = self.get_shortest(X, Y, len(X) - 1, len(Y) - 1, keys, items)
		return item



9

In [94]:
'''

Given a given sequence, find the length of the longest decreasing subsequence (LDS) in it.

The longest decreasing subsequence is a subsequence of a given sequence in which the subsequence's elements are in sorted order, highest to lowest, and in which the subsequence is as long as possible.

Input : [0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15]
Output: 6
Explanation: The longest decreasing subsequence is [12, 10, 9, 5, 3] having length 5; the input sequence has no 6–member decreasing subsequences.

The longest decreasing subsequence is not necessarily unique. For instance, [12, 10, 6, 5, 3] is another decreasing subsequences of equal length in the same input sequence.

'''


class Solution:
    
    
    def findLDSLength(self, nums: List[int]) -> int:
        if not nums:
            return 0
        dp = [0] * len(nums)
        dp[0] = 1

        for i in range(1, len(nums)):
            for j in range(i):
                if nums[j] > nums[i] and dp[j] > dp[i]:
                    dp[i] = dp[j] 
            dp[i] += 1
        return max(dp)
        
Solution().findLDSLength([0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15])

5

In [104]:
'''

Given a sequence, find the longest bitonic subsequence in which the subsequence's elements are first sorted in increasing order, then in decreasing order.

Input: [4, 2, 5, 9, 7, 6, 10, 3, 1]
Output: 7
Explanation: The longest bitonic subsequence is [4, 5, 9, 7, 6, 3, 1].

For sequences sorted in increasing or decreasing order, the output is the same as the input sequence, i.e.,

Input: [1, 2, 3, 4, 5]
Output: 5

Input: [5, 4, 3, 2, 1]
Output: 5

'''


class Solution:
    
    def get_lis(self, nums, i, el):
        if i < 0:
            return 0
        if i == 0:
            if nums[i] < el:
                return 1
            return 0
        dp = [0] * (i+1)
        if nums[i] < el:
            dp[0] = 1
        else:
            dp[0] = 0
        for k in range(1, i+1):
            for l in range(k):
                if el > nums[k] > nums[l] and dp[k] < dp[l]:
                    dp[k] = dp[l]
            if nums[k] < el:
                dp[k] += 1
            else:
                dp[k] = 0
        return max(dp)
    
    def get_lds(self, nums, i, el):
        if i >= len(nums):
            return 0
        if i == len(nums) - 1:
            if nums[i] < el:
                return 1
            return 0
        dp = [0] * (len(nums) - i)
        if nums[i] < el:
            dp[0] = 1
        else:
            dp[0] = 0
        for k in range(1, len(nums) - i):
            for l in range(k):
                if el > nums[i+l] > nums[i+k] and dp[k] < dp[l]:
                    dp[k] = dp[l]
            if nums[i+k] < el:
                dp[k] += 1
            else:
                dp[k] = 0
        return max(dp)


    def get_length(self, nums, i):
        
        left = self.get_lis(nums, i - 1, nums[i])
        right = self.get_lds(nums, i + 1, nums[i])
        
        return left + right + 1
    
    def findLBSLength(self, nums: List[int]) -> int:
        if not nums:
            return 0
        max_length = 0
        for i in range(len(nums)):
            length = self.get_length(nums, i)
            if max_length < length:
                max_length = length
        return max_length
Solution().findLBSLength([4, 2, 5, 9, 7, 6, 10, 3, 1])

7

In [112]:
'''

Given a sequence, find a subsequence of it such that the subsequence sum is as high as possible and the subsequence's elements are sorted in ascending order.

Input: [0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11]
Output: 34
Explanation: The maximum sum increasing subsequence is [8, 12, 14] which has sum 34.

Input: [-4, -3, -2, -1]
Output: 0
Explanation: The maximum sum increasing subsequence is [] which has sum 0.

'''


class Solution:
    def findMSISLength(self, nums: List[int]) -> int:
        if not nums:
            return 0
        
        dp = [0] * len(nums)
        
        dp[0] = nums[0] if nums[0] >= 0 else 0
        n = len(nums)
        max_sum = 0
        for j in range(1, n):
            if nums[j] <= 0:
                dp[j] = 0
            else:
                dp[j] = nums[j]
            for i in range(j):
                if nums[j] > nums[i]:
                    dp[j] = max([dp[j], dp[i] + nums[j]])
        return max(dp)
Solution().findMSISLength( [4, 2, 5, 9, 7, 6, 10, 3, 1])

[4, 2, 9, 18, 16, 15, 28, 5, 1]


28

In [113]:
'''

Given two words, find the minimum number of single-character edits required to transform one word into the other. An edit can be insertion, deletion, or substitution and each edit carries a unit cost.

Input: X = 'kitten', Y = 'sitting'
Output: 3
Explanation: A minimal edit script that transforms the 'kitten' into 'sitting' is:

kitten —> sitten (substitution of 's' for 'k')
sitten —> sittin (substitution of 'i' for 'e')
sittin —> sitting (insertion of 'g' at the end)

'''


class Solution:

    def transform(self, X, m, Y, n, keys):
        if (X, m, n, Y) in keys:
            return keys[(X, m, n, Y)] 
        if m == 0:
            keys[(X, m, n, Y)] = n
            return n
        if n == 0:
            keys[(X, m, n, Y)] = m
            return m
        dst = 0 if X[m-1] == Y[n-1] else 1
        
        keys[(X, m, n, Y)] = min([
            self.transform(X, m-1, Y, n, keys) + 1, # delete
            self.transform(X, m, Y, n-1, keys) + 1, # insertion
            self.transform(X, m-1, Y, n-1, keys) + dst, # substitution
        ])
        return keys[(X, m, n, Y)]
    
    def findMinDistance(self, X: str, Y: str) -> int:
        m, n = len(X), len(Y)
        
        dst = self.transform(X, m, Y, n, dict())
          
        return dst