In [1]:
import numpy as np
from copy import deepcopy

In [2]:
A = np.random.randint(0, 20, size=(20,))
B = np.random.randint(0, 20, size=(45,))
C= np.random.randint(0, 52, size=(10,))

In [3]:
A

array([19,  0, 15, 11, 14,  5, 18, 18, 15, 12,  0, 12,  7, 13, 10, 10,  9,
       18, 16,  0])

In [4]:
def insert_sort(array, reverse=False):
    cmp_func = lambda a, b:  a < b if reverse else a>b
    for j in range(1, len(array) ):
        current = array[j]
        i = j -1

        while i >=0 and cmp_func(array[i] , current):
            array[i+1] = array[i]
            i = i-1
        array[i+1] = current



In [5]:
insert_sort(A, reverse=True)
print(A)
insert_sort(A)
print(A)

[19 18 18 18 16 15 15 14 13 12 12 11 10 10  9  7  5  0  0  0]
[ 0  0  0  5  7  9 10 10 11 12 12 13 14 15 15 16 18 18 18 19]


In [6]:
A


array([ 0,  0,  0,  5,  7,  9, 10, 10, 11, 12, 12, 13, 14, 15, 15, 16, 18,
       18, 18, 19])

In [7]:
def merge(array1, array2):
    array =[]
    while 1:
        if array1 and not array2:
            array.extend(array1)
            break
        if array2 and not array1:
            array.extend(array2)
            break
        if array1 and array1[0] <= array2[0]:
            array.append(array1.pop(0))
        else:
            array.append(array2.pop(0))
    return array
    # assert len(array1) == len(array2)
    # array1.append(float("inf"))
    # array2.append(float("inf"))
    # i, j= 0, 0
    # new_array = []
    # for k in range(len(array2) + len(array2) - 2):
    #     if array1[i] <=array2[j]:
    #         new_array.append(array1[i])
    #         i +=1
    #     else:
    #         new_array.append(array2[j])
    #         j += 1
    # return new_array



def merge_sort(array):
    if len(array) == 1:
        return [array[0]]
    separator = len(array) // 2
    left = merge_sort(array[:separator])
    right = merge_sort(array[separator:])
    mg= merge(left, right)
    return mg


print(B)
merge_sort(B)



[15  6 18  6  5 18 11 17 10 10 12  2 18 10  9 15  6  6 13  1 16 11  9  5
 18 12 18 16 16 12  8 19  0 12 14  0 15  4  7  8  3  2 19 13 16]


[0,
 0,
 1,
 2,
 2,
 3,
 4,
 5,
 5,
 6,
 6,
 6,
 6,
 7,
 8,
 8,
 9,
 9,
 10,
 10,
 10,
 11,
 11,
 12,
 12,
 12,
 12,
 13,
 13,
 14,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 17,
 18,
 18,
 18,
 18,
 18,
 19,
 19]

In [8]:
def insertion_sort_merge(arr, key):
    for i in range(len(arr)):
        if key <arr[i]:
            arr.insert(i, key)
            break
    return arr



def recursive_insertion_sort(arr):
    if len(arr) == 1:
        return [arr[0]]
    key = arr[-1]
    return insertion_sort_merge(recursive_insertion_sort(arr[:-1]), key)




recursive_insertion_sort(C)

[2, 6, 9, 15, 20, 23, 30, 33, 47, 50]

In [9]:
from math import floor

class Node:

    def __init__(self, indice, value):
        self.indice = indice
        self.value = value
        self.parent = None
        self.left = None
        self.right = None

    def __repr__(self):
        """
                       # f"parent={self.parent}," \

        :return:
        """
        return f"Node(indice={self.indice}, " \
               f"value={self.value}," \

class HeapList:

    def __init__(self, data= None):
        self.nodes = []
        self._data = data
        self.data = self.initialize(data)

    @staticmethod
    def initialize(data):
        nodes = []
        for i, v in enumerate(data, 1):
            node = Node(i, v)
            if i ==1:
                nodes.append(node)
                continue
            parent = nodes[floor(i//2) -1 ]
            node = Node(i, v)

            if i % 2 ==0 :
                parent.left  = node
            else:
                parent.right = node
            node.parent = parent
            nodes.append(node)
        return nodes

heap = HeapList([16, 14, 10,8,7,9,3, 2,4, 1])

In [10]:
print(heap.data[4].left)

Node(indice=10, value=1,


In [11]:
class Heap(object):

    def __init__(self, data=None):
        data = [] if data is None else data
        self.data = data
        self.heapsize = len(self.data)

    def parent(self, i):
        # if i>1:
        return i//2
        # return None

    def left(self, i):
        # if 2*i < len(self.data) + 1:
            # return self.data[2*i - 1]
        return 2*i
        # return None

    def right(self, i):
        # if (2*i + 1) < len(self.data) + 1:
            # return self.data[2*i]
            return 2*i + 1
        # return None

    def max_heapify(self, i):
        left, right = self.left(i), self.right(i)
        largest = i
        if left <= self.heapsize and self.data[left -1] > self.data[largest - 1]:
            largest = left
        if right <=self.heapsize and self.data[right - 1] > self.data[largest - 1]:
            largest = right
        if largest != i:
            tmp = self.data[i-1]
            self.data[i-1] = self.data[largest-1]
            self.data[largest-1] = tmp
            self.max_heapify(largest)

    def sort(self):
        """O(n*lgn)"""
        self.build_max_heap()
        for i in range(len(self.data), 1, -1):
            tmp = self.data[i-1]
            self.data[i-1] = self.data[0]
            self.data[0] = tmp
            self.heapsize -= 1
            self.max_heapify(1)



    def build_max_heap(self):
        for i in range(len(self.data) // 2, 0, -1):
            self.max_heapify(i)

    def __getitem__(self, item):
        return self.data[item]

    def __len__(self):
        return len(self.data)

heap = Heap([ 27, 17, 3 , 16, 13,  10, 1, 5, 7, 12,
              4, 8, 9, 0])
heap.sort()
print(heap.data)

[0, 1, 3, 4, 5, 7, 8, 9, 10, 12, 13, 16, 17, 27]


In [12]:
for i in range(1, len(heap.data) + 1):
    print(i, heap[i-1], heap.parent(i),
          heap.left(i), heap.right(i))

1 0 0 2 3
2 1 1 4 5
3 3 1 6 7
4 4 2 8 9
5 5 2 10 11
6 7 3 12 13
7 8 3 14 15
8 9 4 16 17
9 10 4 18 19
10 12 5 20 21
11 13 5 22 23
12 16 6 24 25
13 17 6 26 27
14 27 7 28 29


In [13]:
len(heap)


14

In [14]:
heap.sort()

In [15]:
heap.data


[1, 3, 4, 5, 7, 8, 9, 10, 12, 13, 16, 17, 27, 0]

In [16]:
# Priority queue
class RangeError(Exception):
    pass

class PriorityQueue(Heap):
    def __init__(self, data):
        super(PriorityQueue, self).__init__(data)

    def heap_maximum(self):
        return self.data[0]

    def heap_extract_max(self):
        if self.heapsize < 1:
            raise RangeError
        max_ = self.data[0]
        self.data[0] = self.data[self.heapsize - 1]
        self.heapsize -= 1
        self.max_heapify(1)

        return max_
    def heap_increase_key(self, i, key):
        if key < self.data[i]:
            raise ValueError
        print(self.data[i])

        self.data[i] = key
        while i >0 and A[self.parent(i) - 1] < A[i]:
            parent = self.parent(i) - 1
            print(parent, self.data[parent])
            parent_val = self.data[parent]
            self.data[parent] = self.data[i]
            self.data[i] = parent_val
            i = parent

pq = PriorityQueue([ 27, 17, 3 , 16, 13,  10, 1, 5, 7, 12,
              4, 8, 9, 0])
print(pq.heap_extract_max())
pq.heap_increase_key(3, 25)
print(pq.heap_extract_max())
print(pq.heap_extract_max())
print(pq.heap_extract_max())

27
7
0 17
25
16
17


In [17]:
"""QuickSort"""
def partition(data,p, r):
        x = data[r]
        i = p - 1
        for j in range(p, r):
            if data[j] <= x:
                i +=1
                dj = data[j]
                data[j] = data[i]
                data[i] = dj
        ar = data[r]
        data[r] = data[i+1]
        data[i+1] = ar
        return i + 1

def quicksort(data, p=0, r= None):
    if r is None:
        r = len(data) - 1

    if p < r:
        q = partition(data, p, r)
        quicksort(data, p, q-1)
        quicksort(data, q+1, r)

data = [ 27, 17, 3 , 16, 13,-1,  10, 1, 5, 7, 12, 4, 8, 9, 11]
# data = [ 27, 17, 3 , 16, 13,  10, 12]

quicksort(data)
print(data)

[-1, 1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 16, 17, 27]


In [18]:
data = np.random.random((25)) * np.random.randint(0,100,size=25) + 1
data = np.array(data, np.int32)
print(data)

[15 69 25 37 45  5 10 21  4  2  2 26  9 12 33 16 23 10 16 14 55 67 72  1
  8]


In [19]:
"""Merge Sort"""

def merge_sort(data):
    def merge(P1, P2):
        s1 = len(P1)
        s2 = len(P2)
        P = []
        i, j = 0, 0
        s = len(P1) + len(P2)

        while i + j < s:
            if (i < s1 and j < s2 and P1[i] <= P2[j]) or j >= s2:
                P.append(P1[i])
                i += 1
            elif (i < s1 and j < s2 and P2[j] < P1[i]) or i >= s1:
                P.append(P2[j])
                j += 1
        return P

    size = len(data)
    if size == 1:
        return data
    p1, p2 = data[0:size // 2], data[size // 2:]
    return merge( merge_sort(p1), merge_sort(p2))


d = deepcopy(data)
print(merge_sort(d))
print(d)

[1, 2, 2, 4, 5, 8, 9, 10, 10, 12, 14, 15, 16, 16, 21, 23, 25, 26, 33, 37, 45, 55, 67, 69, 72]
[15 69 25 37 45  5 10 21  4  2  2 26  9 12 33 16 23 10 16 14 55 67 72  1
  8]


In [20]:
def binary_search(data, v, low=0, high=-1):
    """Search in sorted array. O(lgn)"""
    if len(data)== 1:
        return low if data[0] == v else None
    p1, p2 = data[:len(data)//2], data[len(data)//2:]
    return binary_search(p1, v, low=low) if p1[-1] >= v \
        else binary_search(p2, v, low=low + len(data)//2)
print(binary_search(merge_sort(d), 52))
print(merge_sort(d)[22])


None
67


In [21]:
def find_element_for_sum(data, s):
    """0(nlgn)"""
    data = merge_sort(data) # O(nlgn)
    for i in range(len(data)):
        target = binary_search(data[i+1:len(data)], s - data[i])
        if target is not None:
            print("d", data[i], data[target + i +1 ], data[i] + data[target+i])
            return i, target+i+1

    return [None] * 2

x1, x2 = find_element_for_sum(d, s=84)
print(x1, x2)

d 12 72 81
9 24


In [30]:

def inversion(data):
    """Give an algorithm that determines the number of inversions in any permutation
on n elements in ‚.n lg n/ worst-case time"""
    if len(data) == 1:
        return 0
    left, right =data[:len(data)//2], data[len(data)//2:]
    c_left = inversion(left)
    c_right = inversion(right)
    # c = c1 + c2
    c = c_left + c_right
    i=j=k=0
    print(f"Left: {left}, Right: {right}")
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            data[k] = left[i]
            i +=1
        else:
            c += len(left) - i
            data[k] = right[j]
            j +=1
        k +=1

    while i < len(left):
        data[k] = left[i]
        i +=1
        k +=1
    while j < len(right):
        data[k] = right[j]

        j +=1
        k +=1

    for _j in range(j, len(right)):
        data[_j] = right[_j]

    return c




dd= [2,3,8,6,1]
inversion(dd)

Left: [2], Right: [3]
Left: [6], Right: [1]
Left: [8], Right: [1, 6]
Left: [2, 3], Right: [1, 6, 8]


5