In [1]:
import numpy as np


In [2]:
A = np.random.randint(0, 20, size=(20,))
B = np.random.randint(0, 20, size=(45,))
C= np.random.randint(0, 52, size=(10,))

In [3]:
A

array([ 4, 11,  8,  1, 13, 18,  0, 10,  2,  4, 14, 16,  7, 11, 19, 19,  8,
        8,  3,  6])

In [4]:
def insert_sort(array, reverse=False):
    cmp_func = lambda a, b:  a < b if reverse else a>b
    for j in range(1, len(array) ):
        current = array[j]
        i = j -1

        while i >=0 and cmp_func(array[i] , current):
            array[i+1] = array[i]
            i = i-1
        array[i+1] = current



In [5]:
insert_sort(A, reverse=True)
print(A)
insert_sort(A)
print(A)

[19 19 18 16 14 13 11 11 10  8  8  8  7  6  4  4  3  2  1  0]
[ 0  1  2  3  4  4  6  7  8  8  8 10 11 11 13 14 16 18 19 19]


In [6]:
A


array([ 0,  1,  2,  3,  4,  4,  6,  7,  8,  8,  8, 10, 11, 11, 13, 14, 16,
       18, 19, 19])

In [7]:
def merge(array1, array2):
    array =[]
    while 1:
        if array1 and not array2:
            array.extend(array1)
            break
        if array2 and not array1:
            array.extend(array2)
            break
        if array1 and array1[0] <= array2[0]:
            array.append(array1.pop(0))
        else:
            array.append(array2.pop(0))
    return array
    # assert len(array1) == len(array2)
    # array1.append(float("inf"))
    # array2.append(float("inf"))
    # i, j= 0, 0
    # new_array = []
    # for k in range(len(array2) + len(array2) - 2):
    #     if array1[i] <=array2[j]:
    #         new_array.append(array1[i])
    #         i +=1
    #     else:
    #         new_array.append(array2[j])
    #         j += 1
    # return new_array



def merge_sort(array):
    if len(array) == 1:
        return [array[0]]
    separator = len(array) // 2
    left = merge_sort(array[:separator])
    right = merge_sort(array[separator:])
    mg= merge(left, right)
    return mg


print(B)
merge_sort(B)



[11  6 10 10 10  3  4  1  8 12 19 16  6  7 12 12  7 15  8  6 13  6  9  0
  8  6  8 12 19  9 13 12 14  5 16 13  0  5  9 19 11 19  5  5 12]


[0,
 0,
 1,
 3,
 4,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 10,
 10,
 10,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 14,
 15,
 16,
 16,
 19,
 19,
 19,
 19]

In [8]:
def insertion_sort_merge(arr, key):
    for i in range(len(arr)):
        if key <arr[i]:
            arr.insert(i, key)
            break
    return arr



def recursive_insertion_sort(arr):
    if len(arr) == 1:
        return [arr[0]]
    key = arr[-1]
    return insertion_sort_merge(recursive_insertion_sort(arr[:-1]), key)




recursive_insertion_sort(C)

[5, 12, 15, 17, 17, 21]

In [9]:
from math import floor

class Node:

    def __init__(self, indice, value):
        self.indice = indice
        self.value = value
        self.parent = None
        self.left = None
        self.right = None

    def __repr__(self):
        """
                       # f"parent={self.parent}," \

        :return:
        """
        return f"Node(indice={self.indice}, " \
               f"value={self.value}," \

class HeapList:

    def __init__(self, data= None):
        self.nodes = []
        self._data = data
        self.data = self.initialize(data)

    @staticmethod
    def initialize(data):
        nodes = []
        for i, v in enumerate(data, 1):
            node = Node(i, v)
            if i ==1:
                nodes.append(node)
                continue
            parent = nodes[floor(i//2) -1 ]
            node = Node(i, v)

            if i % 2 ==0 :
                parent.left  = node
            else:
                parent.right = node
            node.parent = parent
            nodes.append(node)
        return nodes

heap = HeapList([16, 14, 10,8,7,9,3, 2,4, 1])

In [10]:
print(heap.data[4].left)

Node(indice=10, value=1,


In [11]:
class Heap(object):

    def __init__(self, data=None):
        data = [] if data is None else data
        self.data = data
        self.heapsize = len(self.data)

    def parent(self, i):
        # if i>1:
        return i//2
        # return None

    def left(self, i):
        # if 2*i < len(self.data) + 1:
            # return self.data[2*i - 1]
        return 2*i
        # return None

    def right(self, i):
        # if (2*i + 1) < len(self.data) + 1:
            # return self.data[2*i]
            return 2*i + 1
        # return None

    def max_heapify(self, i):
        left, right = self.left(i), self.right(i)
        largest = i
        if left <= self.heapsize and self.data[left -1] > self.data[largest - 1]:
            largest = left
        if right <=self.heapsize and self.data[right - 1] > self.data[largest - 1]:
            largest = right
        if largest != i:
            tmp = self.data[i-1]
            self.data[i-1] = self.data[largest-1]
            self.data[largest-1] = tmp
            self.max_heapify(largest)

    def sort(self):
        """O(n*lgn)"""
        self.build_max_heap()
        for i in range(len(self.data), 1, -1):
            tmp = self.data[i-1]
            self.data[i-1] = self.data[0]
            self.data[0] = tmp
            self.heapsize -= 1
            self.max_heapify(1)



    def build_max_heap(self):
        for i in range(len(self.data) // 2, 0, -1):
            self.max_heapify(i)

    def __getitem__(self, item):
        return self.data[item]

    def __len__(self):
        return len(self.data)

heap = Heap([ 27, 17, 3 , 16, 13,  10, 1, 5, 7, 12,
              4, 8, 9, 0])
heap.sort()
print(heap.data)

[0, 1, 3, 4, 5, 7, 8, 9, 10, 12, 13, 16, 17, 27]


In [12]:
for i in range(1, len(heap.data) + 1):
    print(i, heap[i-1], heap.parent(i),
          heap.left(i), heap.right(i))

1 0 0 2 3
2 1 1 4 5
3 3 1 6 7
4 4 2 8 9
5 5 2 10 11
6 7 3 12 13
7 8 3 14 15
8 9 4 16 17
9 10 4 18 19
10 12 5 20 21
11 13 5 22 23
12 16 6 24 25
13 17 6 26 27
14 27 7 28 29


In [13]:
len(heap)


14

In [14]:
heap.sort()

In [15]:
heap.data


[1, 3, 4, 5, 7, 8, 9, 10, 12, 13, 16, 17, 27, 0]